# Generated by Django 4.0.3 on 2022-11-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('place', models.CharField(max_length=50)),
                ('userpin', models.CharField(max_length=6)),
                ('userpic', models.FileField(null=True, upload_to='')),
                ('userbloodgroup', models.CharField(max_length=10)),
                ('userdob', models.CharField(max_length=2)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReqBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('mob', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('pic', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userbloodgroup', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('place', models.CharField(max_length=50)),
                ('userdob', models.DateField(max_length=8)),
                ('weight', models.CharField(max_length=3, null=True)),
                ('status', models.CharField(max_length=40, null=True)),
                ('donationdate', models.DateTimeField(auto_now_add=True)),
                ('depremark', models.CharField(max_length=300, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
