# Generated by Django 4.0.3 on 2022-11-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('mob', models.CharField(max_length=15, null=True)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('appointmentdate', models.DateField(max_length=10)),
                ('regulardonor', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=40, null=True)),
                ('departmentremark', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
