# Generated by Django 4.0.3 on 2022-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_donorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorappointment',
            name='updationdate',
            field=models.DateField(null=True),
        ),
    ]
