# Generated by Django 4.0.3 on 2022-11-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_donorappointment_updationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('mob', models.CharField(max_length=15, null=True)),
                ('amount', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=100)),
                ('rwithpatient', models.CharField(max_length=10)),
                ('documentpic', models.FileField(null=True, upload_to='')),
                ('patientpic', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departmentremark', models.CharField(max_length=300, null=True)),
                ('updationdate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
