# Generated by Django 4.0.3 on 2022-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reqcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqcampaign',
            name='adminremark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='reqcampaign',
            name='rwithpatient',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
