# Generated by Django 5.0.6 on 2024-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_reqcampaign_adminremark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorappointment',
            name='bloodbank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reqcampaign',
            name='depstatus',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reqcampaign',
            name='selecteddepartment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
